### ISSUE TITLE
QoL: Make mobile time display shorter

### ISSUE THREAD

**Issue by lad6558** [DormSoup/dormsoup#14] opened 2024-09-21 03:47 UTC
Right now the mobile time shows as "Sep 24 at 5:00PM". Sometimes when there are four tags, the user can't see the location. We can shorter it to something like "09/24 17:00"

**Comment by gulkily** [comment] 2024-10-27 20:23
I think I can do this.

**Comment by lad6558** [comment] 2024-10-27 20:41
<img width="336" alt="image" src="https://github.com/user-attachments/assets/b7e2fcf9-1840-4385-be38-7fbe75199f56">

**Comment by lad6558** [comment] 2024-10-27 20:42
Only appears on actual mobile. Does not appear in desktop resized browser

**Comment by gabrc52** [comment] 2024-10-27 20:44
![Screenshot_20241027-164338](https://github.com/user-attachments/assets/7275fc69-6c92-44c6-8f83-5446b99f3b3e)

mfw my phone isn't "actual mobile". Can't reproduce on Android

**Comment by gabrc52** [comment] 2024-10-27 20:48
https://github.com/DormSoup/dormsoup/blob/main/app/components/EventDate.tsx

**Comment by gabrc52** [comment] 2024-11-10 01:11
This was fixed through #19. For next time, you can write "Fixes #14" in the PR description and it will close the issue when merged.

**Closed as completed** 2024-11-10 01:11 UTC
